### ISSUE TITLE
Cómo imprimir en pantalla

### ISSUE THREAD

**Issue by odflor** [t-edson/P65Pas#1]
Hola t-edson:

Muy promisorio tu proyecto, me gustó cómo solucionaste el problema de los pokes.

Estoy queriendo mostrar información por la pantalla un simple hola mundo y algunas cosas más.

Basicamente quiero hacer lo que hacia el print "(corazon video reverso)" y el print "hola mundo".

Cómo habría de hacerlo?, espero que no haga falta recurrir al assembler.

Supuse que como no encontre un writeln habria que empezar a escribir desde la dirección 1024 en adelante (así como assembler). La ventaja es que aquí por el concepto de unidad de pascal se pueden hacer funciones que pueden ser llamadas desde otros programas, aunque quedaría mejor si esas funciones ya estuvieran incorporadas al compilador.

Ya sabes esas funciones "comunes", limpiar la pantalla, cambiar el tipo de consola (grafica, multicolor, texto), dibujar lineas, puntos, manejo del SID, y bla, bla bla.

Personalmente me animo a hacer esas funciones porque conozco mucho de la implementación de hardware de la commodore 64 gracias a la enorme documentación que por suerte todavía existe.

En resumen felicidades por tus logros con este proyecto y personalmente me gustaría hacer algun juego con el o tal vez algun editor de texto o planilla electronica, sólo por diversión.

**Comment by t-edson** [comment]
Hola odflor.

Disculpa no haber respondido antes. He estado algo ocupado en el trabajo y me he desconectado un poco.
P65Pas es un proyecto que recién empieza. Solo tiene implementadas algunas funciones básicas.  Lo más desarrollado es la IDE, porque viene desde otro de mis proyectos: PicPas.
Uno de mis objetivos, es también poder desarrollar un juego en este compilador, pero de momento, falta mucho por implementar. Aún no hay soporte para cadenas, como tal y tampoco para arreglos.

Precisamente, yo también vi la necesidad de poder imprimir mensajes como un "Hola mundo" en la pantalla del Commodore, pero vi que era necesario disponer del tipo de dato "String", que aún no existe. Y para disponer de un String, se debe poder primero implementar arreglos, y para los arreglos, se debe implementar primero punteros. De modo que, lo último que estuve revisando, fue el tema de los punteros y para eso hay que definir bien lo que se llama "almacenamiento" de variables. Tengo unos apuntes que necesito plasmar en código, aún.  Pero es tema de tiempo.

**Comment by t-edson** [comment]
En cuanto a la función writeln(). Sería posible implmentarla internamente, sin manejar punteros ni nada, pero sería una función del sistema. Pero P65Pas se diseñó para trabajar como compilador del CPU6502, más que del Commodore. Eso significa que las funciones del sistema, deben ser lo más generales posible, y no centradas en una sola plataforma.
De todas formas, hace poco he incluido un modo nuevo, mediante la directiva {$COMMODOR64} que perimte que el compilador trabaje en ese modo y ahí si tendría sentido disponer de rutinas internas de escritura en pantalla.
Voy a ver si puedo implementar un writlen() sencillo que trabaje en modo COMMODORE64, para poder mostrar texto en pantalla.
De todas formas, este proyecto está abierto a colaboraciones y mientras más personas colaboren, más grande y completo se hará.

Saludos

**Comment by odflor** [comment]
Don Tito:
Excelente, yo me imagino que es mucho trabajo, yo se muy poco de compiladores, pero de lo que sé, se que es muy complejo de implementar. Pero de programar para Commodore 64 se más y de lo que sé me permite saber que tu trabajo es muy bueno y muy promisorio.
Yo veo incluso la posibilidad de escribir un "sistema operativo" o mejor dicho algo parecido a lo que era el "dos shell" de MSDOS con tu compilador. Y juegos que exploten todas las capacidades de la commodore.
En un futuro tal vez se pueda incluso usar el Z80 y el Video DAC (80 columnas) de la commodore 128 y otros perifericos nuevos que los muchachos están desarrollando.
Como verás quedé muy entusiasmado con el potencial que vi en tu trabajo.
Si crees que te puedo ayudar con algo, sólo avísame. Principalmente creo que podría ayudarte haciendo algunas APIs cuando estemos más avanzados.
Saludos!

Atte,...
Lic. Oscar D. Flor R.
Analista de Sistemas
Tel. (595) 981 683-482 

    El martes, 25 de septiembre de 2018 10:48:09 a. m. GMT-4, Tito Hinostroza <notifications@github.com> escribió:  
 
 
Hola odflor.

Disculpa no haber respondido antes. He estado algo ocupado en el trabajo y me he desconectado un poco.
P65Pas es un proyecto que recién empieza. Solo tiene implementadas algunas funciones básicas. Lo más desarrollado es la IDE, porque viene desde otro de mis proyectos: PicPas.
Uno de mis objetivos, es también poder desarrollar un juego en este compilador, pero de momento, falta mucho por implementar. Aún no hay soporte para cadenas, como tal y tampoco para arreglos.

Precisamente, yo también vi la necesidad de poder imprimir mensajes como un "Hola mundo" en la pantalla del Commodore, pero vi que era necesario disponer del tipo de dato "String", que aún no existe. Y para disponer de un String, se debe poder primero implementar arreglos, y para los arreglos, se debe implementar primero punteros. De modo que, lo último que estuve revisando, fue el tema de los punteros y para eso hay que definir bien lo que se llama "almacenamiento" de variables. Tengo unos apuntes que necesito plasmar en código, aún. Pero es tema de tiempo.

**Comment by t-edson** [comment]
Yo también veo mucho potencial en un compilador para el 6502. Ese es uno de los motivos que me animó a emprender este proyecto. Pero no olvidar que P65Pas es más que un simple compilador. Es una IDE, con compilador y depurador integrado. Y no olvidar que el compilador puede hacer también de ensamblador.
Hay muchas formas en las que se puede apoyar en el proyecto:
- Documentación.
- Códigos de ejemplo.
- Códigos de prueba.
- Traducciones (La IDE de P65Pas, maneja pro ahora Inglés, Español, Alemán, Frances, Ruso y Ucraniano).
- Temas para la IDE.
- Desarrollo del compilador.
- Desarrollo de la IDE.
- Desarrollo del depurador.
- Difusión.
- Donaciones.

Ahora si manejas el ensamblador del 6502, podrías implementar las diversas operaciones que están pendientes en el compilador, como las operaciones aritméticas o lógicas o algunas funciones del sistema.
Sería cuestión de que te adentres un poco en el código y aprendas cómo incluir las rutinas en ensamblador. Todo el desarrollo está hecho en Lazarus y en Object Pascal, pero no es necesario dominar el lenguaje para aportar en el código. El proyecto está bastante modularizado como para trabajarse en forma independiente.

**Comment by Ekcloeb** [comment]
Hola t-edison,

sorry my english is not good. I had see your project P65pas. Very very good. I'am not a Pascalprogramer, so it is not easy to read your sourcecode. But I make over 35 years programs for the 6502/65C02. I like to implement the 16-bit integerarithmetic for your project. The spanish comments are also not helpfull for me. In witch part i can find the 8 bit integerarithmetic? Is it possible to implement the 16 bit arithmetic in this part? Thanks for you information.
In the 8 bit arithmetic is an error: the 8 bit + 8 bit translate to 8 bit and 8 bit.

**Comment by t-edson** [comment]
Hi Ekcloeb.

Pascal is easy to read even in the Object Pascal dialect. I prefer it instead of C++.

P65Pas has only 8 bits unsigned integer aritmethic. It's the BYTE type.

Data types are created in the constructor TGenCodBas.Create() in the unit GenCodBas_PIC16. Here you can create new signed or unsigned types. The WORD type is created here too. 

If you create a new signed type I recomend to use the names INT8 or INT16.

After new type is created you need to implemente operations on this type. It's done in the method TGenCod.DefCompiler() in the unit "GenCod_PIC16". You have to follow the conventons like use the A register to return results, if type is one byte length.

Tell me if you have problems on implementing. I will review the code and translate some comments to english. Don't forget this compiler is in a very beginning status.

**Comment by Ekcloeb** [comment]
Hola t-edison,

thanks for your fast reaction. I will look at this parts. 

First I like to implement the word type unsigned (Add/Sub/Rol/Ror/Asl/Lsr/Inc/Dec/Mul/Div). By any question for the implementation or conventons I call you again.

Greetings from Germany

**Comment by t-edson** [comment]
Hi.
I've reviewed some the code (There is still much to do). It's updated now.

I've fixed some bugs and advanced in the implementation of the boolean type.

The "word" type (as unsigned 16 bits integer) is already defined, with a minimal support.

Greetings.

**Comment by t-edson** [comment]
Version 0.4. It includes support for declaring strings as arrays of char and improved ASM blocks.
![image](https://user-images.githubusercontent.com/7736802/59468291-45437c80-8df7-11e9-968d-8ef0d0282a3f.png)

**Comment by t-edson** [comment]
Currently, with the version 0.6, the compiler can print text in the Commodore 64 screen  using arrays of chars:

```
uses Commodore64;
var 
  str: []char = 'HELLO' + #0;
begin
  STROUT(@str);
  asm rts end 
end.
```
So I consider the main issue is closed.

Actualmente, con la versión 0.6, es posible imprimir texto en la pantalla del Commodore 64, así que considero el tema cerrado.

**Comment by Ekcloeb** [comment]
Hello,

 

with this Mail come two units for the AppleII. May be it is helpfull for AppleII user or for some parts of the compiler.

 

Greetings

 
 

Gesendet: Mittwoch, 26. Juni 2019 um 19:28 Uhr
Von: "Tito Hinostroza" <notifications@github.com>
An: "t-edson/P65Pas" <P65Pas@noreply.github.com>
Cc: "Ekcloeb" <tom_boelcke@gmx.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [t-edson/P65Pas] Cómo imprimir en pantalla (#1)


Closed #1.

**Comment by t-edson** [comment]
Hi.

Sorry. I cannot see any attachment.

**Comment by Ekcloeb** [comment]
{$SET_STATE_RAM '0100-01FF:SFR,C000-CFFF:SFR,D000-FFFF:SFR'}  // stack/IO-page/rom
  {$SET_DATA_ADDR ''}
  {$SET_DATA_ADDR '00FA-00FF'}

  {$ORG $2000}

unit AppleII;

//-------------------------------------------------------------------------------

interface
const
	basl	= $28;                                        // basisadresse bildschirmzeile nr. 1
	bash	= $29;
	bas2l	= $2A;                                        // basisadresse bildschirmzeile nr. 2
	bas2h	= $2B;

  keybuf = $0200;                                     // AppleII keybordbuffer
  keybup = $02ff;                                     // current read pos in keyboardbuffer
  bytin  = $fd0c;                                     // get one char from keyboard  - rom
  bytout = $fded;                                     // put one char/byte to screen - rom

var
  wkpt1 : word absolute $eb;                          // AppleII - Adress of input or data <--- Applesoftbasic
  wkpt2 : word absolute $ed;
  wkpt3 : byte absolute $ef;
  strlen: byte absolute $d7;                           // store for current stringlen

  dez1: array[2] of byte = [10,100];                                     // need for decimal out/in byte
  dez2: array[8] of byte = [$0a, $00, $64, $00, $e8, $03, $10, $27];     // need for dezimal out/in word

  basladr: array[24] of	byte	= [$00,$80,$00,$80,$00,$80,$00,$80,$28,$A8,$28,$A8,$28,$A8,$28,$A8,$50,$D0,$50,$D0,$50,$D0,$50,$D0];
  bashadr: array[24] of byte	= [$04,$04,$05,$05,$06,$06,$07,$07,$04,$04,$05,$05,$06,$06,$07,$07,$04,$04,$05,$05,$06,$06,$07,$07];


    procedure strin(B: byte; A: word register) :byte;           // strin(maxlen, @string):reallen or strin(maxlen, keybuf):reallen
    procedure hexinb :byte;
    procedure hexinw :word;
    procedure bininb :byte;
    procedure bininw :word;
    procedure decinb :byte;
    procedure decinw :word;

    procedure clrscr;
    procedure setcurxy(X: byte registerA; Y: byte registerY);
    procedure setcurx(X: byte registerA);


    procedure strout(A: word register);                         // strout(@string) or strout(keybuf)
    procedure hexout(A: byte registerA);
    procedure hexout(A: word register);
    procedure decout(A: byte registerA);
    procedure decout(A: word);
    procedure binout(A: byte registerA);
    procedure binout(A: word register);

    procedure conout(A:byte registerA);
    procedure conin :byte;

// parse keybuf for valid input - procedures can be override (to much valid characters without delimiter)

    procedure shexin;
    procedure sbinin;
    procedure sdecin;

// -------------------------------------------------------------------------------

implementation

  procedure conin :byte;

    begin
        asm
          jsr bytin
        end
    end;

  procedure strin(B: byte; A: word register) :byte;                 // strin(maxlen, @string):reallen or strin(maxlen, keybuf):reallen
    begin
    wkpt1:= A;
    asm
              ldy #$00                     ; reset charcounter
      loop:   sty wkpt3
	            jsr bytin                    ; get char - this procedure destroy Yreg
              ldy wkpt3

              cmp #$8d                     ; return ?     AppleII bit 7 on
              beq return
              cmp #$88                     ; rubout ?
              beq rubout
              cmp #$a0                     ; other controlchar ?
              bcc loop                     ; yes - ignore

              cpy B                        ; buffer full ?
              bcs loop                     ; yes - ignore
              sta (wkpt1),y                ; no -  put char to buffer
              jsr bytout                   ; screenecho
              iny                          ; charcounter+1
              bne loop                     ; get next char

      rubout: cpy #$00                     ; Xcur on pos 0 ?
              beq loop                     ; yes - ignore
              jsr bytout                   ; Xcursor-1
              lda #$a0
              jsr bytout                   ; erase char on screen
              lda #$88
              jsr bytout
              dey                          ; charcounter-1
              lda #$00
              sta (wkpt1),y                ; erase char(x) in keybuf
              beq loop                     ; all time

      return: lda #$00
              sta (wkpt1),y                ; set string endmarker
              sta keybup                   ; set current readpos to begin keyboardbuffer
              tya                          ; stringlen to regA
    end
    end;
  procedure hexinb :byte;
  begin
    strlen := strin(2, keybuf);                // __E = current inputlen
    shexin;
    asm
	    lda __IX.low
    end
  end;
  procedure hexinw :word;
    begin
      strlen:= strin(4,keybuf);
      shexin;
      asm
        lda __IX.high
        sta __H
        lda __IX.low
      end
    end;
  procedure bininb :byte;
  begin
    strlen:= strin(8, keybuf);
    sbinin;
    asm
      lda __IX.low
    end
  end;
  procedure bininw :word;
    begin
      strlen:= strin(16, keybuf);
      sbinin;
      asm
	      lda __IX.high
        sta __H
        lda __IX.low
      end

    end;
  procedure decinb :byte;
    begin
      strlen:= strin(3, keybuf);
      sdecin;
      asm
        lda __IX.low
      end
    end;
  procedure decinw :word;
    begin
      strlen:=strin(5, keybuf);
      sdecin;
      asm
	      lda __IX.high
        sta __H
        lda __IX.low
      end
    end;

  procedure conout(A: byte registerA);
  begin
    asm
      ora #$80
      jsr bytout
    end
  end;
  procedure binout(A: word register);
      begin
        asm
          sta __U
        end
        binout(__H);
        binout(__U);
      end;
  procedure binout(A: byte registerA);
    begin
      asm
              ldx #$07
      loop2:  rol
              pha
              lda #$b0
              bcc loop
              lda #$b1
      loop:   jsr bytout
              pla
              dex
              bpl loop2
      end
    end;
  procedure hexout(A: byte registerA);
    begin
    asm
	              pha
                lsr
                lsr
                lsr
                lsr
                jsr nibble
                pla
                and #%00001111

      nibble:   clc
                adc #176
                cmp #186
                bcc loop

                clc
                adc #7
      loop:     jsr bytout
    end
  end;
  procedure hexout(A: word register);
  begin
      asm
        sta __U
      end
      hexout(__H);
      hexout(__U);
  end;
  procedure decout(A: byte registerA);
    begin
     asm
                  beq zero             ; regA = 0 - print '0'
                  ldx #$80
                  stx __H              ; set zerobefore? marker
                  ldx #$01             ; set pointer dez1.array
        loop2:    ldy #$00             ; reset digitcounter
        loop1:    cmp dez1,x           ; >= tabbyte ?
                  bcc loop             ; no - next digit
                  iny                  ; digit=digit+1
                  sbc dez1,x           ; regA=regA-dez1.array,x
                  bne loop1
        loop:     pha                  ; store regA
                  tya                  ; digit to regA
                  bit __H              ; only zeros before ?
                  bpl loop3            ; no - print digit
                  cpy #$00             ; only zeros before and digit = 0 ?
                  beq loop4            ; yes - don't print digit
        loop3:    asl __H              ; reset zerobefore? marker
                  ora #$b0             ; for appleII highbit on
                  jsr bytout           ; print digit
        loop4:    pla                  ; restore regA
                  dex                  ; 10^2 digit and 10^1 digit done ?
                  bpl loop2            ; no - calc next digit
         zero:    ora #$b0             ; print one zero or digit 10^0
                  jsr bytout
     end

  end;
  procedure decout(A: word);
    begin
      asm
                  ldx #$00            ; set leadedzeros? marker
                  stx __H
                  ldx #$07            ; set pointer array.dez2.highbyte
         wloop2:  ldy #$00            ; reset digitcounter

         wloop:   lda A.high          ; restore A.highbyte
                  cmp dez2,x          ; > array.dez.highbyte.x - check zero and/or not print digit
                  bcc endsub          ; < array.dez.highbyte.x - check zero and/or not print digit
                  beq chklb           ; = array.dez.highbyte.x - check lowbyte
                  dex                 ; set pointer = arraydez.lowbyte
                  lda A.low
                  sec                 ; A = A - arraydez(x)
        wloop1:   sbc dez2,x
                  sta A.low
                  inx
                  lda A.high
                  sbc dez2,x
                  sta A.high
                  iny                 ; inc digitcounter
                  bne wloop           ; all time

        chklb:    lda A.low           ; restore A.lowbyte
                  dex                 ; set pointer = arraydez.lowbyte
                  cmp dez2,x          ; valid ?
                  bcs wloop1          ; >= array.dez.lowbyte.x = valid digit

                  inx                 ; set pointer = arraydez.high
        endsub:   tya                 ; digit to regA
                  bne nonull          ; digit <> 0 - print
                  cmp __H             ; leaded zero ?
                  beq next            ; yes - no print

        nonull:   ora #$b0            ; appleII need bit 7 on
                  inc __H             ; __H = counter for valid digits and marker for leaded zeros
                  jsr bytout          ; conout digit
        next:     dex                 ; pointer=pointer-2
                  dex
                  bpl wloop2          ; calc next digit

                  lda A.low           ; load last digit
                  ora #$b0            ; appleII need bit 7 on
                  jsr bytout          ; conout last digit
        quit:

      end
    end;
  procedure strout(A: word register);
    begin
      wkpt1:=A;
      asm
                ldy #$00
        loop:   lda (wkpt1),y
                beq loop1           ; endmarker $00
                ora #$80
                jsr bytout          ; appleII need bit 7 on
                iny
                bne loop
        loop1:
     end
   end;

  procedure setcurxy(X: byte registerA; Y:byte registerY);
  begin
    asm
	              cmp $21             ; wndwdth
	              bcs	loop
	              clc
	              adc	$20             ; wndlft
	              sta	$24		          ; 40col CurX
                bit $c01f           ; 40col or 80col activ ?
                bpl loop		        ; is 40col
                sta $057b           ; 80col CurX
          loop:	tya
	              clc
	              adc	$22             ; wndtop
	              cmp	$23             ; wndbtm
	              bcs	exit
	              tay
	              LDA	bashadr,Y
	              STA	bash
	              LDA	basladr,Y
	              STA	basl
	              tya
	              sta	$25
	              bit	$c01f
	              bpl	exit
	              sta	$05fb
          exit:
    end

 end;
  procedure setcurx(X: byte registerA);
  begin
    asm
	              cmp $21             ; wndwdth
	              bcs	loop
	              clc
	              adc	$20             ; wndlft
	              sta	$24		          ; 40col CurX
                bit $c01f           ; 40col or 80col activ ?
                bpl loop		        ; is 40col
                sta $057b           ; 80col CurX
			loop:
    end

  end;
  procedure clrscr;
  begin
    asm
      jsr $fc58
    end
  end;

// inside unit

  procedure shexin;                                             // parse keybuf for valid hex input
    begin
    __IX:=0;                                                       // stop by 4 nibble or delimiter
    asm
                ldy #$04
        next:   jsr nibble        ; get hexnibble
                bcs exit1
                asl __IX.low      ; one nibble up
                rol __IX.high
                asl __IX.low
                rol __IX.high
                asl __IX.low
                rol __IX.high
                asl __IX.low
                rol __IX.high
                dey
                bne next
                beq exit1

       nibble:  ldx keybup
                lda keybuf,x
                sec
                sbc #$b0
                cmp #23
                bcs exit          ; = >'F'
                cmp #10
                bcc num           ; = '0..9)
                cmp #17
                bcc exit          ; = between '0..9' and 'A..F'
                sbc #7
       num:     ora __IX.low
                sta __IX.low
                inc keybup        ; set new  current readpos in keybordbuffer
       exit1:   clc
                rts
       exit:    sec
     end
   end;
  procedure sbinin;                                             // parse keybuf for valid bin input
    begin
      __IX:= 0;                                                      // stop by 16 bit or delimiter
      asm
                ldy #$10
        loop:   ldx keybup
                lda keybuf,x      ; get bin-digit
                cmp #$b0
                beq ok
                cmp #$b1
                beq ok
                rts

        ok:     lsr
                rol __IX.low
                rol __IX.high
                inc keybup
                dey
                bne loop
      end
    end;
  procedure sdecin;                                             // parse keybuf for valid dec input
  begin
    __IX:= 0;                                                      // stop by 5 digits or delimiter
    asm
                ldy #$00            ; digitcounter:= 0
      loop:     ldx keybup          ; posX:= keybup
                lda keybuf,x        ; regA:= keybuf.posX
                sec
                sbc #$b0
      	        cmp #10	            ; if regA>9 then exit
	              bcs exit
                pha                 ; store digit on stack
                inc keybup
                iny
                cpy #$06
                bcs exit
                bcc loop

       exit:    cpy #$00            ; empty string ?
                beq ende            ; yes
                pla
                sta __IX.low        ; add 10^0
                ldx #$00            ; set tabcounter
        outer:  dey                 ; digitcounter-1
                beq ende            ; all digits done
                pla                 ; get next digits -  10^1 to 10^4
                beq loop3           ; is zero - nothing to do
                sta __H             ; store digit
        inner:  clc
                lda __IX.low
                adc dez2,x
                sta __IX.low
                inx
                lda __IX.high
                adc dez2,x
                sta __IX.high
                dex
                dec __H
                bne inner
        loop3:  inx
                inx
                bne outer
        ende:
    end
  end;

end.



unit commands;

interface
  uses AppleII;

  var
    Areg:      byte absolute $45;
    Xreg:      byte absolute $46;
    Yreg:      byte absolute $47;
    Preg:      byte absolute $48;
    Sreg:      byte absolute $49;                                         // bit0 = C, bit1 = Z, bit6 = V, bit7 = N

    regchar:   array[5] of  byte = [$41, $58, $59, $50, $53];             // "AXYPS"


 procedure incr(A: word register) ;                                                // pointer to var word
 procedure decr(A: word register) ;                                                // pointer to var word
 procedure rol(A: word register);                                                  //       "
 procedure ror(A: word register);                                                  //       "

 procedure setbit(B: byte registerX; A: word register);                            // setbit(bit0-7,varadr) to var byte
 procedure clrbit(B: byte registerX; A: word register);                            // clrbit(bit0-7,varadr) to var byte
 procedure tstbit(B: byte registerX; A: word register): boolean;                   // tstbit(bit0-7,varadr) :boolean
 procedure setbit(B: word; A: word register);
 procedure clrbit(B: word; A: word register);
 procedure tstbit(B: word; A: word register): boolean;

 procedure left(A: word register; B: byte registerX): word;                        // left(adressstring,len) :keybuf
 procedure right(A: word register; B: byte registerX): word;                       // right(adressstring,len) :keybuf
 procedure mid(A: word register; B: byte registerY; C: byte registerX): word;      // mid(adresstring, xpos, len):keybuf
 procedure setstr(A:word);

 procedure instr(B: word; A: word register): byte;                                 // instr(searchintostring, searchstring)
 procedure strlen(A: word register): byte;                                         // strlen(adressstring): stringlen

 procedure peek(A: word register): byte;                                           // get one byte from memory
 procedure poke(B: byte; A: word register);                                        // put one byte to   memory
 procedure week(A: word register): word;                                           // get one word from memory
 procedure woke(B: word; A: word register);                                        // put one word to   memory

 procedure dumpmem(adr: word register; banz: byte registerY; lanz: byte registerX);

 procedure call(A: word register);                                                 // call a machineroutine at adress A
 procedure setreg(reg: char registerA; B: byte registerY);                         // set reg before call
 procedure getreg(reg: char registerA): byte;                                      // get reg after  call

 procedure dectCPU: byte;
//--------------------------------------------------------------------------------------------------

implementation

//  maths

  procedure rol(A: word register);
    begin
      wkpt1:= A;
      asm
	                ldy #$00
                  lda (wkpt1),y
                  asl
                  sta (wkpt1),y
                  iny
                  lda (wkpt1),y
                  rol
                  sta (wkpt1),y
      end
    end;
  procedure ror(A: word register);
    begin
      wkpt1:=A;
      asm
	                ldy #$01
                  lda (wkpt1),y
                  lsr
                  sta (wkpt1),y
                  dey
                  lda (wkpt1),y
                  ror
                  sta (wkpt1),y

      end
    end;
  procedure incr(A: word register);
      begin
        wkpt1:=A;
        asm
                ldy #$00
                lda (wkpt1),y
                tax
                inx
			          bne exit

                txa
                sta (wkpt1),y
                iny
			          lda (wkpt1),y
                tax
                inx
          exit: txa
                sta (wkpt1),y
        end
      end;
  procedure decr(A: word register);
      begin
        wkpt1:=A;
        asm
                  ldy #$00
                  lda (wkpt1),y
			            tax
                  dex
                  cpx #$ff
                  bne exit

                  txa
                  sta (wkpt1),y
                  iny
                  lda (wkpt1),y
                  tax
                  dex
          exit:   txa
                  sta (wkpt1),y
        end
      end;

//  bitfield

  procedure setbit(B: byte registerX; A: word register);
      begin
        wkpt1:=A;
        asm
	                  txa
                    ldy #$00
                    ora (wkpt1),y
                    sta (wkpt1),y
        end
      end;
  procedure clrbit(B: byte registerX; A: word register);
      begin
        wkpt1:=A;
        asm
	                  txa
                    eor #$ff
                    ldy #$00
                    and (wkpt1),y
                    sta (wkpt1),y
        end
      end;
  procedure tstbit(B: byte registerX; A: word register): boolean;
      begin
        wkpt1:=A;
        asm
	                  txa
                    ldy #$00
                    and (wkpt1),y
                    beq exit
                    lda #$01
          exit:
        end
      end;
  procedure setbit(B: word; A: word register);
    begin
      wkpt1:=A;
        asm
                    ldy #$00
	                  lda B.low
                    beq loop
                    ora (wkpt1),y
                    sta (wkpt1),y
          loop:     iny
                    lda B.high
                    beq exit
                    ora (wkpt1),y
                    sta (wkpt1),y
          exit:
        end
    end;
  procedure clrbit(B: word; A: word register);
    begin
      wkpt1:=A;
        asm
	                  ldy #$00
                    lda B.low
                    beq loop
                    eor #$ff
                    and (wkpt1),y
                    sta (wkpt1),y
          loop:     iny
                    lda B.high
                    beq exit
                    eor #$ff
                    and (wkpt1),y
                    sta (wkpt1),y
          exit:
        end
    end;
  procedure tstbit(B: word; A: word register): boolean;
    begin
      wkpt1:=A;
      asm
	                  ldy #$00
                    lda B.low
                    and (wkpt1),y
                    bne exit
        loop:       iny
                    lda B.high
                    and (wkpt1),y
        exit:
      end
    end;

//  strings

  procedure left(A: word register; B: byte registerX): word;
    begin
    wkpt1:= A;
    asm
                dex                     ; charcounter - 1 (0 to n-1)
                ldy #$00                ; set stringpointer
      loop:     lda (wkpt1),y
                beq exit                ; stringend ? - yes
                sta keybuf,y
                iny
                dex
                bpl loop

      exit:     lda #$02
                sta __H
                lda #$00
                sta keybuf,y
    end
  end;
  procedure right(A: word register; B: byte registerX): word;
    var
      plen: byte;
      tlen: byte;
      xpos: byte;
    begin
      wkpt1:= A;
      plen := B;
      tlen := strlen(wkpt1);
      asm
                lda tlen                ; textpart>textstring ?
                sec
                sbc plen
                bcc exit                ; yes
                tay                     ; set xpos

                ldx #$00                ; set stringbegin to zero
        loop: 	lda (wkpt1),y
                beq exit                ; stringend ? - yes
                sta keybuf,x
                iny
                inx
                cpx plen
                bcc loop

        exit:   lda #$02
                sta __H
                lda #$00
                sta keybuf,x
      end
    end;
  procedure mid(A: word register; B: byte registerY; C: byte registerX): word;      // mid(adresstring, xpos, len)
    var
      xpos: byte;
      plen: byte;
      tlen: byte;

    begin
      wkpt1:= A;                          // pointer to string
      xpos := B;
      plen := C;
      tlen := strlen(wkpt1);
      asm
                  ldy xpos
                  cpy tlen                 ; xpos >= stringlen?
                  bcs exit                 ; yes

                  ldx #$00
                  dey
        loop:     lda (wkpt1),y
                  beq exit
                  sta keybuf,x
                  iny
                  inx
                  cpx plen
                  bcc loop

         exit:    lda #$02
                  sta __H
                  lda #$00
                  sta keybuf,x
      end
    end;
  procedure setstr(A:word);
  begin
    wkpt1:=A;
    asm
	              ldy #$00
      loop:     lda $0200,y
                beq exit
                sta (wkpt1),y
                iny
                bne loop
      exit:     sta (wkpt1),y
    end
  end;

  procedure instr(B: word; A: word register): byte;                                 // instr(searchstring, searchintostring)
    var
      wk1len: byte;
      wk2len: byte;
    begin
      wkpt1 := A;                             // set adress/len searchintostring
      wk1len:= strlen(wkpt1);
      wk2len:= strlen(B);                     // set len searchstring

      asm
                  ldx #$03
                  lda B.low
                  sta inner,x
                  inx
                  lda B.high
                  sta inner,x

                  lda wk1len                ; textpart>textstring ?
                  sec                       ; and set textlen-partlen
                  sbc wk2len
                  bcc exit                  ; yes - textpart>textstring
                  sta wk1len
                  inc wk1len


                  ldx #$00                  ; set textpartpointer
                  stx __H                   ; store textstringpointer

        outer:    ldy __H                   ; restore textstringpointer

        inner:    lda (wkpt1),y             ; textstringchar = partstringchar ?
                  cmp $FFFF,x
                  bne next                  ; no
                                            ; yes
                  cpx #$00                  ; first char searchstring is valid then
                  bne loop
                  sty __H                   ; store textstringpointer

        loop:     iny
                  inx                       ; found ?
                  cpx wk2len
                  bcs found                 ; yes
                  bcc inner

        next:     cpx #$00
                  beq loop1
                  ldx #$00
                  beq outer

        loop1:    iny
                  cpy wk1len
                  bcc inner
        exit:     lda #$00                  ; result = 0                  - textpart not found or textpart>textstring
                  rts

        found:    ldy __H
                  iny
                  tya
      end
    end;
  procedure strlen(A: word register):byte;
    begin
      asm
	              ldx #$01                ; set pointer
                  sta loop,x
                  inx
                  lda __H
                  sta loop,x

                  ldx #$00                ; check stringlen
        loop:     lda $FFFF,x
                  beq next
                  inx
                  bne loop

        next:     txa                     ; return strlen
      end
    end;

//  memory

  procedure peek(A: word register): byte;
    begin
      wkpt1:= A;
      asm
                  ldy #$00
                  lda (wkpt1),y
      end
    end;
  procedure poke(B: byte; A: word register);
    begin
      wkpt1:= A;
      asm
                  ldy #$00
                  lda B
                  sta (wkpt1),y
      end

    end;
  procedure week(A:word register): word;
    begin
      wkpt1:= A;
      asm
        ldy #$01
        lda (wkpt1),y
        sta __H
        dey
        lda (wkpt1),y
      end
    end;
  procedure woke(B: word; A: word register);
    begin
      wkpt1:=A;
      asm
	      ldy #$00
        lda B.low
        sta (wkpt1),y
        iny
        lda B.high
        sta (wkpt1),y
      end
    end;

  procedure dumpmem(adr: word register; banz: byte registerY; lanz: byte registerX);  // dumpmem(adresse,byteanz,lineanz)
    var
      i: byte;

    begin
      wkpt1:=adr;

      asm
                    sty i
            loop2:  lda wkpt1.high        ; adress
                    jsr $fdda
                    lda wkpt1.low
                    jsr $fdda
	                  lda #$ba
                    jsr $fded
                    lda #$a0
                    jsr $fded

	                  ldy #$00              ; bytes
            loop:   lda (wkpt1),y
                    jsr $fdda
                    lda #$a0
                    jsr $fded
                    iny
                    cpy i
                    bcc loop

                    jsr $fded               ; ascci
                    ldy #$00
            loop5:  lda (wkpt1),y
                    and #127
                    cmp #32
                    bcs loop3
                    lda #174
            loop3:  cmp #127
                    bne loop4
                    lda #174
            loop4:  ora #128
                    jsr $fded
                    iny
                    cpy i
                    bcc loop5

                    clc
                    lda wkpt1
                    adc i
                    sta wkpt1
                    bcc loop1
                    inc wkpt1.high
            loop1:  lda #$8d
                    jsr $fded
                    dex
                    bne loop2
      end
    end;

  procedure call(A: word register);
    begin
      asm
                   ldx #$01       ; set jsr-adres
	               sta go,x
                   inx
                   lda __H
                   sta go,x

                   lda Preg       ; set regs
                   pha
                   lda Areg
                   ldx Xreg
                   ldy Yreg
                   plp

        go:        jsr $ffff      ; dummy !

                   php
                   sta Areg       ; store regs
                   pla
                   sta Preg
                   stx Xreg
                   sty Yreg
      end
    end;
  procedure setreg(reg: char registerA; B: byte registerY);
  begin
    asm
                  ldx #$04
      loop:       cmp regchar,x
                  beq enz
                  dex
                  bpl loop
                  rts
      enz:        sty Areg,x
    end
  end;
  procedure getreg(reg: char registerA): byte;
    begin
      asm
                  ldx #$04
	      loop:     cmp regchar,x
                  beq enz
                  dex
                  bpl loop
                  rts
        enz:      lda Areg,x
      end
    end;

//  CPU

  procedure dectCPU: byte;
    begin
      asm
 		              lda #$99
 		              clc
 		              sed
 		              adc #$01
 		              cld
 		              beq CMOS
	 	              lda #0				            ; is 6502
 		              rts
        CMOS:	    lda #1                    ; is 65c02 or 65816
      end
    end;


end.

**Comment by t-edson** [comment]
OK. I will include.

**Comment by Ekcloeb** [comment]
Sorry, i have forgotten the examples for the apple2 units. I will make and send this next week.

 
 

Gesendet: Sonntag, 01. November 2020 um 01:50 Uhr
Von: "Tito Hinostroza" <notifications@github.com>
An: "t-edson/P65Pas" <P65Pas@noreply.github.com>
Cc: "Ekcloeb" <tom_boelcke@gmx.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [t-edson/P65Pas] Cómo imprimir en pantalla (#1)


 

Hi.

Sorry. I cannot see any attachment.
