### ISSUE TITLE
multiplication support is not complete

### ISSUE THREAD

**Issue by mvdhoning** [t-edson/P65Pas#12]
multiplication support is not complete in the compiler yet

**Comment by t-edson** [comment]
Multiplication operation is implemented in version 0.7.1. Only for byte operands. The result is a word. But if you want to make faster operations it's better to make shift and rotations.
Moreover, if you want to access to a specific position in the Commodore screen, there is a fast function called: PutChar():

```
uses Commodore64;
var 
  row, col: byte;
begin 
  //Fill the screen with character A
  for row:=0 to 24 do
    for col:=0 to 39 do 
      PutChar(col, row, #1);
    end;
  end;
  asm rts end 
end.
```
