### ISSUE TITLE
Example CommodoreScreen doesn't compile

### ISSUE THREAD

**Issue by odflor** [t-edson/P65Pas#14]
Hi:
Testing examples i notice that the example CommodoreScreen.pas doesn't compile.

The error is in the line 12.
The error is "Error en tipos de parámetros de delay_ms()"

If the value of the function is bigger than 255 it compile.
If the value is less than 256 it raises and error...

Thanks and
Best Regards

**Comment by t-edson** [comment]
I confirm it fails. This is because there are some changes with the system function calls. I think this will be solved in next versions. By the moment you can use: 

delay_ms(word(100));
