### ISSUE TITLE
Possibility to use P65Pas with Commodore 128

### ISSUE THREAD

**Issue by odflor** [t-edson/P65Pas#15]
Hi:
I want to use the P65Pas compiler to make some programs for the Commodore 128 in 128 mode plus the 64 mode.
I know the MMU differences between the two modes of operation.
I will need to do a Commodore128.pas unit to for store in the kernels calls such as Commodore64 does.
You know is possible to do this with P65Pas?
I will need to do some kind of library to, to manage common issues. Luckily I have where to copy the routines from other projects.
Best Regards

**Comment by t-edson** [comment]
I think it's possible.
P65Pas is a compiler aimed to compile for the 6502 CPU systems, not for a specific machine. 
And yes. You would need to create a new unit (or more) for the C128 system. I don't know how compatible it's C128 with the C64. If they are very similar, just some minor changes you would need to do in the Commodore64.pas unit.
