### ISSUE TITLE
compiled code doesn't much the asm ... end block

### ISSUE THREAD

**Issue by Squall-FF8** [t-edson/P65Pas#18]
That is a terrible bug! It seems the compiler doesn't calculate the labels inside asm...end block!
Both lines that have <opcode> bmp+2 are wrong!
![image](https://user-images.githubusercontent.com/35965968/68481403-c5073300-023f-11ea-8903-e78aad511608.png)

**Comment by t-edson** [comment]
Yes. This is a terrible bug.  Instruction with labels were only defined to JSR and JMP instructions.
A fix has done in version 0.7.3. But the references to the labels only support the label "bmp", not expressions like "bmp+2". It will require more work to implement this kind of expressions.

**Comment by mvdhoning** [comment]
It would be very nice to be able to do label or var reference with a constant value added to it. E.g. for accessing a part of a large array (see my ticket #28 on that).

**Comment by t-edson** [comment]
Several improves has been added in ASM blocks, in the trunk 0.8, including arithmetic operations in operands for ASM instructions.

**Comment by t-edson** [comment]
Issue is solved in version 0.9.0.
