### ISSUE TITLE
How to "walk" through memory using "pure pascal"

### ISSUE THREAD

**Issue by odflor** [t-edson/P65Pas#2]
Hi Mr.:

** Commodore 64 **

I want to do some "scroll screen routine" to simulate a man walking over a street. I know how to do this in assembler but I want to try it on pascal to see performance.

To do that I need to store on some place of the memory the "street mapping" or "the stage" (in terms of game making).

On the first, i need to copy the first portion of the street from the mapping place to the screen memory and then scroll it to the left (for example) and fill the right left column with new "stret data" from the mapping memory location.

My ask is:

There is a way to use a "variable" to point to a specifically memory location as is shown in the examples, But there is a way to do some kind of "offset" to add to this variable to change the location where I want to write data? As in assembler can do with the x and y registers using acumulator.

I want to copy a part of the memory to other location as a copy/paste of bytes.

There is a example on some basic language aproach to ilustrate to:

var i : byte;
vscreen = $1000; // The first column and line of the commodore 64 text screen

// fill the screen with "@" character
for i := 0 to 255 do
begin
  poke(vscreen + i, 1); // screen code for "@"
end; // for

I do not know if I'm explaining myself well. I want to navigate trough memory from a start point to a offset of locations.

Thanks a Best Regards

**Comment by t-edson** [comment]
Hi. 

> There is a way to use a "variable" to point to a specifically memory location as is shown in the examples

Short answer. Not. Not by now.
Pointers and arrays are not implemented by now. 
I had been redesigning many parts of the compiler to allow pointers and consequently arrays too (they are very related concept). However I haven't had time to finish it. Addresses modes in 6502 are very strange and limited when indexing memory.

> for i := 0 to 255 do
> begin
> poke(vscreen + i, 1); // screen code for "@"
> end; // for

Maybe it would be easy to implement a "poke()" function in P65pas to accomplish this work or maybe ut could be better to implement some function like: "FillMem256(StartAddress, Value)"

**Comment by mvdhoning** [comment]
maybe with 0.4 this is possibe now
```
var i : byte;
vscreen: array [255] of byte absolute $1000;

for i := 0 to 254 do
  vscreen[i]:=1;
end;
```
but not quite yet for now as  that gives a Cannot assing to this opperand error
vscreen[1]:=1; is ok though in the loop but would not accomplish much.
So this is either still a work in progress or a bug. I expect the first.

**Comment by t-edson** [comment]
v0.4 version is closed now.  v0.5 is opened. 

And Yes. this is something not currently supported. 

I've been working a lot on implementing this, but using a solid design. Quickly and limited implementation would be possible but I prefer to do a work of "enginering" not just ptach some code.

Although surprising, this features is related with the getters and setters (methods) concepts, and I want to integrate with INLINE functions, and I've been developing the support for this based on a future implementation of objects (smart records).

In this days I've revised the compiler and I think it's close to be implemented (experimentally) the assign operation for arrays. I will check.

**Comment by t-edson** [comment]
v06.6 of the compiler can now assign values to arrays indexed by variables:

```
uses Commodore64;
var 
  mem: [65535]byte absolute $00;
  i: word;
begin
  i := $400;
  while i<>$600 do
    mem[i] := 65;
    inc(i);
  end;
  asm rts end
end.
```

So I consider the post is closed.
