### ISSUE TITLE
Compiler produces invalid code on first attempt.

### ISSUE THREAD

**Issue by at91rm9200** [t-edson/P65Pas#23]
How to reproduce:
- Start IDE
- Open test2.pas
- Open HelloWorld.pas via Files/Samples/HelloWorld → Editor Tab HelloWorld.pas is active.
- Click on Editor Tab “test2.pas”
- Compile and save test2.prg
- Compile again and see the difference in test2.prg

P65Pas 0.7.5 on Ubuntu Mate 16.04. P65Pas 0.5.0 did not show this problem.

[test2_pas.txt](https://github.com/t-edson/P65Pas/files/4058498/test2_pas.txt)

**Comment by t-edson** [comment]
Hi. 
I have tested in Windows and have not that problem.
Are you running in Ubuntu? If What's the difference you observed?

**Comment by at91rm9200** [comment]
Yes, I run the IDE on Ubuntu 16.04 Mate, 64-Bit. Attached are screenshots which show the steps to reproduce the problem. There is a difference with the local variables bloop1 and bloop2 between the first and the second compiler run. I marked this in red.
![2_opentest2pas](https://user-images.githubusercontent.com/52088967/72647363-b1cbbe80-3978-11ea-8297-1cfd589dddbf.png)
![3_openhelloworldviasamples](https://user-images.githubusercontent.com/52088967/72647366-b55f4580-3978-11ea-9aca-aea27a3c2dd1.png)
![4_clickoneditortabtest2](https://user-images.githubusercontent.com/52088967/72647370-b7c19f80-3978-11ea-8b5a-a146436a1cae.png)
![5_compile1](https://user-images.githubusercontent.com/52088967/72647386-bf814400-3978-11ea-9943-2968c0a9a919.png)
![6_compile2](https://user-images.githubusercontent.com/52088967/72647391-c445f800-3978-11ea-8222-83c18d4ff8c2.png)

**Comment by t-edson** [comment]
OK. I will check later. I'm out of house.

**Comment by t-edson** [comment]
Tested in Ubuntu 16. Recreated. It only happens in Linux. The first compilation is wrong. It allocates bloop1 in zero pages. It's dangeorus I will review the code.

**Comment by t-edson** [comment]
Must be fixed in version 0.7.6. Please check.

**Comment by at91rm9200** [comment]
Thank you. The problem is fixed.
