### ISSUE TITLE
Asm command Jmp has a problem with labels

### ISSUE THREAD

**Issue by Squall-FF8** [t-edson/P65Pas#24]
Here is a simple code:
```
  asm 
loop:
      ...
      jmp loop	 
  end 
```
I receive error: Invalid Address mode

**Comment by t-edson** [comment]
HI. I've doing some changes in the assembler in the last versions. Maybe this feature is broken. I will check.

**Comment by t-edson** [comment]
The issue is fixed, in 0.7.8. Please update.
It's strange I haven't detected this problem before. The assembler was trying to applies the Zero-page address mode to the JMP instruction.

**Comment by Squall-FF8** [comment]
It seems the problem is bigger, not just JMP. In 0.78 now all Bxx have the same issue, so the code:
```
loop:
  ...
  BCC loop
```
Now generate the same error: _Invalid Address mode_

**Comment by t-edson** [comment]
I will check. Some changes done must be affected this part of the code.

**Comment by t-edson** [comment]
0.7.8 is updated. The bug must be fixed. I need to check more. It's really needed some test code for assembler.
