### ISSUE TITLE
SBC does not function properly in debugger

### ISSUE THREAD

**Issue by chillyfeez** [t-edson/P65Pas#26]
SBC functions should subtract an extra 1 when the carry flag is clear, but instead they subtract an extra 1 when the carry is set.

**Comment by t-edson** [comment]
Hi. I was working in a new version with deeply changes in the lexer/parser. However, by the moment, I cannot access to the source code.

**Comment by t-edson** [comment]
SBC execution is fixed in the debugger. Check the last version.
