### ISSUE TITLE
Big CPU drain on Linux

### ISSUE THREAD

**Issue by zbyti** [t-edson/P65Pas#27]
![Screenshot_2020-09-02_11-44-07](https://user-images.githubusercontent.com/14273557/91966161-c5624480-ed11-11ea-9ae0-e82901859abe.png)

**Comment by t-edson** [comment]
Hi. I can confirm there is a high CPU load in the linux version. There is 20% in my Ubuntu 16 system. I'm working in the version 0.8.0, changing several parts of the compiler. I will check the CPU in the new version when ready.

**Comment by t-edson** [comment]
Hi. The last version of P65pas use just one small percent of the RAM in my System.

![image](https://user-images.githubusercontent.com/7736802/185275783-9e961406-8bf4-4cea-be9a-1f34da6ab1b5.png)
