### ISSUE TITLE
support for string (and writeln)

### ISSUE THREAD

**Issue by mvdhoning** [t-edson/P65Pas#3]
It would be nice to get support for a string var type. 
But i fear that might need array/pointer support first.

It would be nice to be able to do something like in the following forum page:
[https://www.lemon64.com/forum/viewtopic.php?t=3296&amp;start=15](https://www.lemon64.com/forum/viewtopic.php?t=3296&amp;start=15)
```
 ; Printing a 0-terminated string of up to 256 byte length to screen 

  LDX #$01    ; Select row 
  LDY #$0a    ; Select column 
  JSR $E50C   ; Set cursor 
  
  LDA #<STRING  ; Load lo-byte of string adress 
  LDY #>STRING  ; Load hi-byte of string adress 
  JSR $AB1E     ; Print string 
  RTS           ; End. 
  
STRING     .text "HELLO WORLD!!!" 
           .byte $00 
``` 
Any easy workarounds to output/define more then one char at a time at this moment?

**Comment by t-edson** [comment]
Hi. You're right. String support is projected after implementing arrays and pointers. I've been working a lot in it, but advanced are just in design not in code. String type in P65Pas would be at the style of Pascal, including an extra byte to the size. But I think the C style "string" could be implemented using array of char, like it really is in C. The closer solution coudl be implement support for declaring array of chars with string initialization and then use the assembler code to manipulate it. I'm going to check if it coud be implemented quickly.

**Comment by t-edson** [comment]
Check the version 0.4. It includes support for declaring strings as arrays of char.
![image](https://user-images.githubusercontent.com/7736802/59468291-45437c80-8df7-11e9-968d-8ef0d0282a3f.png)
The implementation of arrays is partial and pointers are still in development. I will be improving the compiler. By the now this is the better approach to print strings.

**Comment by mvdhoning** [comment]
that does the job for now :-)

was trying to use the same char array to copy directly to screen ram and ran into some issues there.

```
  asm
	  ldx #$00
loop:
    lda str , X
    cmp #0
    beq exit
	  sta screenram , X
	  inx
	  cpx #40
	  bne loop
exit:
  end
```

at first i used lda str,x but that does not seem to get parsed as you force to do a space comma space uppercase X what might be good thing for readability.

also str is not recognized, showing the variables in the compiler output shows that it is surrounded by "" followed by a -> instead of being listed as str EQU adress. So i ended up using $adress in code directly.

also i had to use the variable somewhere else as otherwise the compiler does a good job of leaving it out.

Looking forward to your further improvements of the compiler, keep up the good work.

Maybe in the future it will also be possible to make a procedure out of this assembly code and pass on the adres of the string to it. For now i have fun with const strings and a little bit of code duplicating, but that is c64 programming :-)

**Comment by t-edson** [comment]
That's was a terrible bug. I haven't tested that address mode. It was wrong implemented. 
It's solved now. I have updated the Repo.  It's still version 0.4.
It was implemented too, access to constant from ASM blocks and ABSOLUTE arrays. 
![image](https://user-images.githubusercontent.com/7736802/59547267-b8d1b080-8f01-11e9-8601-93f5ef943d5a.png)

**Comment by mvdhoning** [comment]
works now :-)
making a working writeln function out of it is one for the futere as your compilers gets (even) more feature rich.
i consider the request done and close it.
