### ISSUE TITLE
Can't compile the source

### ISSUE THREAD

**Issue by geraldholdsworth** [t-edson/P65Pas#34]
I've been trying to compile, from the source, for other platforms, as I have a Lazarus setup here which can cross compile to Windows 32/64 bit, Linux 32/64 bit, macOS 32/64 bit, macOS M1 (ARM), Raspbian ARM. However, it is failing with the error:
SynFacilCompletion.pas(292,51) Error: Record or object type expected

The line in question is:
property IconList: TImageList read MenuComplet.IconList write SetIconList;

**Comment by t-edson** [comment]
Hi. 

What version of Lazarus/FPC are you using?

**Comment by geraldholdsworth** [comment]
Lazarus 2.2 and FPC 3.2.2

**Comment by t-edson** [comment]
OK. It's fixed. 
It was because I'm not updating the version 0.7.8.
I'm making all new improves in the branch 0.8. It's experimental for now, however it will be definitively the main version.
Version 0.7.8 will be obsolete soon.

**Comment by geraldholdsworth** [comment]
Cool, thanks.

Just tried again and it now fails on lines 195 and 197 of FrameCfgSynEdit where it doesn't know about eoAutoIndent, so I just commented the whole 'if' structure out. This raises a new issue, when running on macOS - basically, it doesn't (get a read only error after the directories have been created). However, as we're moving to a new version:

Version 0.8.9 - this also won't compile as it requires a package called 'etpackage', which I can't find.

EDIT: found it: https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/epiktimer/

**Comment by t-edson** [comment]
Yes. I use the EpikTimer component. I'll include that information in the README.

Tell me if you've problems on compiling the new version.

**Comment by geraldholdsworth** [comment]
Once I comment out lines 194 to 198 of FrameCfgSynEdit then it compiles fine. Just doesn't run on a Mac...I can look into this, if you like.

**Comment by t-edson** [comment]
Good. I'm using only Windows for development. I can test in Ubuntu too. 
But I haven't a Mac so I will thank you if you can help on that platform.
