### ISSUE TITLE
Crashes upon opening

### ISSUE THREAD

**Issue by geraldholdsworth** [t-edson/P65Pas#35]
I found a bug where the application crashes upon opening.

On investigation, this was caused by the **Timer1** component firing before the **FormConfig** form, which is accessed in the **Timer1** handler, has not been created. This arose when I compiled for macOS, but could easily arise with other platforms.

I have got around this, so far, by setting the **Enabled** property of **Timer1** to off (just untick the box) and then in the **FormShow** handler of **FormPrinciple** just add **Timer1.Enabled:=True** at the end. This is not a perfect solution, but will get around the issue for now. A better solution might be to add this line into the **FormCreate** or **FormShow** of the **FormConfig** form's unit (obviously, **FormPrinciple.Timer1.Enabled:=True**).

I have done this with version 0.8.9, as this is the latest version.

**Comment by t-edson** [comment]
I think the better solution is the first you propose, activating the Timer in the FormPrincipal. I will include it in the next update I will make.

**Comment by geraldholdsworth** [comment]
In hindsight, I agree.

**Comment by t-edson** [comment]
Branch 0.8 is updated and renamed to 0.9. Now Timer is enabled in event OnShow of frmPrincipal.

**Comment by rpmccoy33** [comment]
Hello ...

I have tried running P65pas-win64.exe on 3 Win 10 machines and 1 Win 7 machine,
and it gives message -  " This App can't run on your PC, contact the software publisher "
All are running 64 bit Windows.

Any ideas?  or an older version to try ?

_______________________________________

Ok... I got it running in Github Desktop

Thanks,
R McCoy

**Comment by t-edson** [comment]
I work on Windows 10  - 64 bits. I guess the executable should work well in all 64 bits Windows platforms. I could generate a 32 bits executable too but I think it's not useful in this days.  
Anyway, if you still have problems, you can install Lazarus and rebuild the compiler in your system.

**Comment by geraldholdsworth** [comment]
On my fork of this project I have compiled P65pas for Windows 32 and 64 bits, as well as Linux 32/64 bits, macOS 32/64 bits & ARM (M1), and Raspbian OS (Raspberry Pi). I just tested out the Windows 64 bit version on my Windows 10 and it worked fine.

**Comment by rpmccoy33** [comment]
Thanks for both comments.  I edited my earlier post to show that I got it working.

The file structure with all the Folders must be present for it to work correctly.

Thank you. 
R McCoy
