### ISSUE TITLE
Simple test program cannot be compiled.

### ISSUE THREAD

**Issue by at91rm9200** [t-edson/P65Pas#36]
Hello,

the latest version 0.9.2 fails to compile the following program:

```
program test;
{$MODE PASCAL}

var
  xx: Array[10] of Byte;

procedure Run;
var
   b: Byte;
begin
   for b:= 0 to 9 do begin
      xx[b]:= b;
   end;
end;

begin
   Run;
end.
```

The error messages is: “test3[7,11] Error: Function Run not implemented.”

Version 0.7.6 can compile this without problem.

Regards, Bernd.

**Comment by t-edson** [comment]
I confirmed it. It's fixed now.
It was a consequence of the redesign of the core of the compiler. It was interpreting the function as a FORWARD declaration. Additionally, array support is not complete but the sample code can compile.

**Comment by at91rm9200** [comment]
Thank you.

Regards, Bernd.
