### ISSUE TITLE
Missing unit files

### ISSUE THREAD

**Issue by odflor** [t-edson/P65Pas#38]
Hi:

The files adapter6502.pas and CodeTools6502.pas are missing from repository and dependencies.

I can't compile the compiler with Lazarus without them.

Best Regards

**Comment by t-edson** [comment]
Wow. I didn't realize I've modified the trunk  branch. I've been doing many changes in other branch. Changes are oriented to separate the IDE from compiler, so the compiler will stay as a command line compiler (with a copy of the IDE maybe) and the IDE will be a separated project including the this compiler and others.
I've done many advances on that so I think It's time to merge the project to the trunk.

**Comment by odflor** [comment]
Excelent!

The branch P65Pas 0.7.8 compiles very well!

My intention as allways is to give support for c128 computer.

I will see if I can translate some others kernel routines to add on both c64 and c128

I think there is not need to enable basic rom.

**Comment by t-edson** [comment]
Hi. The "trunk" branch is updated with the new changes. It should compile OK now. 
About the C128, I would need the memory map and the location where to locate the binary compiled program. Then I can create a unit to work with the C128.

**Comment by odflor** [comment]
The C128 have a more complicated memory layout because the 8502 is a 8 bit processor and only can access up to 64k of ram and the c128 have twice of it plus the VDC video memory ram than can be used to store data up to 16k or 64k (if is CR desktop or thin) rise up to 192k. Then a banking aproarch is used and managed with the MMU unit.

At default the BANK 15 configuration is usted.

![imagen](https://user-images.githubusercontent.com/25032803/184167933-6f8e13ae-ebcd-4d97-955a-7238101f1440.png)

**Comment by t-edson** [comment]
I've created the "Commodore128.pas" in "\comp_p65pas\units". It has only simple definitions but can generate a *.prg that can be executed from a BASIC bootloader. Tested in VICE:
![image](https://user-images.githubusercontent.com/7736802/185279107-f0b0c695-daab-413e-95c5-4ca0caf9f441.png)

**Comment by odflor** [comment]
I test it!

Works very well!
