### ISSUE TITLE
more procedure parameters options like register?

### ISSUE THREAD

**Issue by mvdhoning** [t-edson/P65Pas#4]
when adding register to a variable in a procedure declaration the variable gets store in Accumulator so no need to do LDA (the readme confuses me a bit as it says something about W register?)

Next to that the c64 (6510) also has an X and and Y register maybe if register keyword is also used on another parameter its value could get put in Y or X index register? Or with keyword REGISTERY or REGISTERX?

Also the c64 (6510) knows something called indirect indexed adressing that uses a zero page adress to store a vector/pointer ( https://www.c64-wiki.com/wiki/Indirect-indexed_addressing ) so it would be nice if one  added the keyword ZEROPAGE in front of a parameter it stores the adress of variable in zero page temp pointer $4B-$4C.

To illustrate to print multiple texts i now have something like this:
```
procedure WriteXY;
begin
  asm
	  ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
	  sta screenram,Y
	  iny
	  cpx #40
	  bne loop
exit:
  end
end;
```
that i can call like
```
asm
	lda #<MyText2
	ldy #>MyText2
	sta $4B
	sty $4C
end
writexy;
```
where MyText2 is declared as
```
var
  MyText2: []char = 'HELLO WORLD !!!'+#0;
```
with zeropage keyword (or a beter name) i would look like so
```
type
  string = []char;

procedure WriteXY(ZeroPage avalue: string);
etc...

//and calling
WriteXY(MyText2);
``` 

Slowly i am getting the hang of c64 assembly again :-)
Next up for me is to use the same trick for screenram access. As i should be able to calculate the correct base screen adres with row and column and store that at another 0 page adres.

potentialy useable adresses might be
             $4B-$60 Temp Pointer / Data Area
FREKZP $FB-$FE Free 0 space for user programs
BASZPT $FF     Basic Temp Data Area

I think you go the same way for array access so
MyText[2] := 'B' wil become a thing in the future.

i guess all 65xx cpu work similiar in this regard but i only know and relearn the c64 way.

ps declaring the type in a unit does not make the new type work in the main program, guess that is because that is not a simple type anymore and work in progress.

**Comment by t-edson** [comment]
> when adding register to a variable in a procedure declaration the variable gets store in Accumulator so no need to do LDA (the readme confuses me a bit as it says something about W register?)

Sorry. This README was adapted from information of my other compiler for PIC microcontrollers. I've updated the documentation and I will be adding more information according the changes in teh compiler.

> Next to that the c64 (6510) also has an X and and Y register maybe if register keyword is also used on another parameter its value could get put in Y or X index register? Or with keyword REGISTERY or REGISTERX?

I've planned that and it's experimentally implemented in the current 0.5 version. You can download from the Repo. This version will be still openend for changes. Parameter (and even variables) can be declared as REGISTER, REGISTERA, REGISTERX or REGISTERY.

![image](https://user-images.githubusercontent.com/7736802/59641024-9d46ef80-9125-11e9-8c76-2f272a9c378b.png)

**Comment by t-edson** [comment]
> Also the c64 (6510) knows something called indirect indexed adressing that uses a zero page adress to store a vector/pointer ( https://www.c64-wiki.com/wiki/Indirect-indexed_addressing ) so it would be nice if one added the keyword ZEROPAGE in front of a parameter it stores the adress of variable in zero page temp pointer $4B-$4C.

It's experimentally implemented too in the 0.5 version. You can define parameters in any absolute position of memory:

![image](https://user-images.githubusercontent.com/7736802/59641220-60c7c380-9126-11e9-9d17-eb0f62cdaba3.png)

If the parameters are mapped in zero page, compiler will always aoptimize the access.

**Comment by mvdhoning** [comment]
i would not know how to pass on the adress of a variable from pascal to fill a and b.
so i stick to my asm bit before calling the function where i can get the lo and hi byte.
this may be usefull for known adresses like the screen at $0400.

**Comment by t-edson** [comment]
Check the last changes. The operator "@" is implemented. The function addr() too, but it has a particular implementation:

![image](https://user-images.githubusercontent.com/7736802/59781689-ef048c80-9281-11e9-8db4-8bf04572ef67.png)

**Comment by mvdhoning** [comment]
pointers :-) 
and some bugs seem to be fixed also.

```
procedure WriteXY(atext: pointer);
begin
  asm    
    lda atext.low
    ldy atext.high
    sta $4B
    sty $4C
    
    ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
    sta screenram,Y
    iny
    cpx #40
    bne loop
exit:
  end
end;
```
this implementation can be improved by using your zero page absolute adressing example. giving 2 pascal functions one exepting the word pointer calling the second one accepting 2 zero page adressed bytes.

```
procedure WriteXYint(alow: byte absolute $4B; ahigh: byte absolute $4C);
begin
  asm
  
	  ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
	  sta screenram,Y
	  iny
	  cpx #40
	  bne loop
exit:
  end
end; 

procedure WriteXY(atext: pointer);
begin  
  WriteXYint(atext.low, atext.high);
end;
```

ps writexyint needs to be declared in the unit publicly before writexy so not private procedures

**Comment by mvdhoning** [comment]
so i guess this issue can be closed as there a are now registera, registery and registerx and absolute adres settings for parameters with zero page support and even pointer support.

```
procedure WriteXY(atext: pointer absolute $4B);
begin 
  asm
  
    ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
    sta screenram,Y
    iny
    cpx #40
    bne loop
exit:
  end 
end;
```

seems to do all magic on one :-) as it autofills the word in $4B and $C :-)

```
    ;writexy(@MyText2);
      $08B9 A9 19    LDA #$19 
      $08BB 85 4B    STA $4B 
      $08BD A9 08    LDA #$08 
      $08BF 85 4C    STA $4C 
      $08C1 20 73 08 JSR $0873
```

**Comment by t-edson** [comment]
Units have very basic support by now. I will review later. By now I'm working on types definitions, arrays and pointers.
