### ISSUE TITLE
Problems with Word

### ISSUE THREAD

**Issue by Squall-FF8** [t-edson/P65Pas#43]
In the example bellow, there are 2 problems:
1. The one that compiler gives.
2. Generated code - it work only when  `i < 256`
`    ;adr_Sprite2_Data[i] := 1;`
`      $081F A9 01    LDA #$01 `
`      $0821 A6 F8    LDX i@0 `
`      $0823 9D 00 10 STA $1000,X `

![image](https://user-images.githubusercontent.com/35965968/199088533-e103a2d2-3a54-4b78-bb82-45405ac319fc.png)

**Comment by t-edson** [comment]
Hi. 
Maybe you're using an old version of P65Pas. Check the last update in Github.
I can compile it right with the trunk version.  
![image](https://user-images.githubusercontent.com/7736802/199295656-05fd6189-c34c-4f1d-8ffa-92be9a709b17.png)

**Comment by Squall-FF8** [comment]
It seems now all is working. 
If somebody else has similar problems, just download the latest version from trunc (**not release**)!
