### ISSUE TITLE
Long string causes a range check error.

### ISSUE THREAD

**Issue by Skertan** [t-edson/P65Pas#55]
Hello,
```Delphi
program NewProgram;
uses Commodore64;
var
  text: array [] of char = '256 Bytes long: This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.This is a long Text.';
begin
  STROUT(@text);
end.
```
When a text is longer than 255 Bytes it causes an range check error with the options OK or ABORT.
This happens since the latest version, previous versions were ok.

**Comment by t-edson** [comment]
I've updated the array initialization routine. Long arrays can be initialized now. But I'm not sure STROUT() can show long arrays
