### ISSUE TITLE
Problem in evaluating the constants

### ISSUE THREAD

**Issue by Squall-FF8** [t-edson/P65Pas#59]
```Delphi
const
  spr1_Address1 = 1 << 15;
```
This code generate error:
`Dialog[25,5] Error: Numeric value exceeds a byte range.`

**Comment by t-edson** [comment]
"byte << byte" is expected to generate a byte in the compiler. so it generates a range error.
Use this:
```
const
  spr1_Address1 = word(1) << 15;  
```
