### ISSUE TITLE
trying to do some byte calculation gives string error?

### ISSUE THREAD

**Issue by mvdhoning** [t-edson/P65Pas#8]
partial code:
```
procedure TestCalculation(arow: byte; acol: byte);
  
implementation

procedure TestCalculation(arow: byte; acol: byte);
var
  vresult: byte;
begin
  //vresult := (arow*40) + acol;
  vresult := arow * 40;
end; 
````
error:
`LibScreen[66,23] Error: Illegal Operation: (byte) := (string)`

Did not realize that arow that is declared as a byte when multiplied with 40 becomes a string :-)

in another function used as a 2nd parameter is get this error on trying multiplying:
`LibScreen[155,19] Error: Illegal Operation: (byte) := (null)`

ps i know when using higher values this could overflow byte boundaries.

maybe give a nicer error until multiplications is implemented ( i asume it is not yet implemented as it is not easy on the c64 with assembly [https://codebase64.org/doku.php?id=base:multiplication_and_division](https://codebase64.org/doku.php?id=base:multiplication_and_division)  [https://codebase64.org/doku.php?id=base:machine_language_tutorial_part_4](https://codebase64.org/doku.php?id=base:machine_language_tutorial_part_4) )

**Comment by t-edson** [comment]
Artimethic operation are not fully implemented yet. Maybe the best way is to use procedures and ASM to implement by now. Or some libraries. I'm changing the design of the Code generator.

**Comment by mvdhoning** [comment]
work in progress code for calculation of screen adres from row/col in assembly
```
procedure WriteXY(atext: pointer absolute $4B; arow: byte; col: byte);
begin   
  asm
    lda #$04
    sta screenposhi
    lda #$00
    sta screenposlo
    ldx #$00
    cpx arow
    beq addcol
add: clc		
     lda screenposlo
     adc #40
     sta screenposlo
     bcc ok             
     inc screenposhi     
ok:  inx
     cpx arow
     bne add
addcol: 
     clc		
     lda screenposlo
     adc col
     sta screenposlo
     bcc ok2             
     inc screenposhi
ok2:     
    ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
    sta ($FE),Y
    iny
    cpy #40
    bne loop
exit:
  end 
end;
```
next up for me is optimizing this and/or trying to do the rows for loop and adding 40 for each row in pascal code as i might not need multiplication here

**Comment by mvdhoning** [comment]
adding in the for loop does not seem to work:
```
procedure WriteXY(atext: pointer absolute $4B; arow: byte; col: byte);
var i: byte;
begin 
  screenpos:=$0400;

  for i:=0 to arow do
    screenpos := screenpos + 40;
  end;
  screenpos := screenpos + col;
  
  screenposlo:=screenpos.low;
  screenposhi:=screenpos.high;
  
  asm
    ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
	  sta ($FE),Y
	  iny
	  cpy #40
	  bne loop
exit:
  end
end;
```

gives
```
__WriteXY:
    ;screenpos:=$0400;
      $0878 A9 00    LDA #$00 
      $087A 8D 1C 08 STA $081C 
      $087D A9 04    LDA #$04 
      $087F 8D 1D 08 STA $081D 
    ;for i:=0 to arow do
      $0882 A9 00    LDA #$00 
      $0884 8D 18 08 STA $0818 
      $0887 AD 16 08 LDA $0816 
      $088A CD 18 08 CMP $0818 
      $088D B0 1F    BCS $08AE 
    ;screenpos := screenpos + 40;
      $088F 18       CLC  
      $0890 AD 1C 08 LDA $081C 
      $0893 69 28    ADC #$28 
      $0895 AA       TAX  
      $0896 AD 1D 08 LDA $081D 
      $0899 69 00    ADC #$00 
      $089B 8D 15 08 STA $0815 
      $089E 8A       TXA  
      $089F 8D 1C 08 STA $081C 
      $08A2 AD 15 08 LDA $0815 
      $08A5 8D 1D 08 STA $081D 
    ;end;
      $08A8 EE 18 08 INC $0818 
      $08AB 4C 87 08 JMP $0887 
    ;screenpos := screenpos + col;
      $08AE 18       CLC  
      $08AF AD 1C 08 LDA $081C 
      $08B2 6D 17 08 ADC $0817 
      $08B5 AA       TAX  
      $08B6 AD 1D 08 LDA $081D 
      $08B9 69 00    ADC #$00 
      $08BB 8D 15 08 STA $0815 
      $08BE 8A       TXA  
      $08BF 8D 1C 08 STA $081C 
      $08C2 AD 15 08 LDA $0815 
      $08C5 8D 1D 08 STA $081D 
    ;screenposlo:=screenpos.low;
      $08C8 AD 1C 08 LDA $081C 
      $08CB 85 FE    STA $FE 
    ;screenposhi:=screenpos.high;
      $08CD AD 1D 08 LDA $081D 
      $08D0 85 FF    STA $FF 
    ;ldy #0
      $08D2 A0 00    LDY #$00 
    ;lda ($4B),Y
      $08D4 B1 4B    LDA $(4B),Y 
    ;cmp #0
      $08D6 C9 00    CMP #$00 
    ;beq exit
      $08D8 F0 07    BEQ $08E1 
    ;sta ($FE),Y
      $08DA 91 FE    STA $(FE),Y 
    ;iny
      $08DC C8       INY  
    ;cpy #40
      $08DD C0 28    CPY #$28 
    ;bne loop
      $08DF D0 F3    BNE $08D4 
    ;end;
      $08E1 60       RTS
```

**Comment by t-edson** [comment]
I haven't tested but it seems to be OK. 
What's the problem with that code?

**Comment by t-edson** [comment]
I found the problem. The branch for the FOR is wrong generated (inverted logic). Now is fixed. Some observations:

The loop must be:

```
for i:=1 to arow do
    screenpos := screenpos + 40;
end;
```

And: Why not declared "screenpos" directly in $FE?

**Comment by mvdhoning** [comment]
now it works :-)
```
procedure WriteXY(atext: pointer absolute $4B; arow: byte; col: byte);
var 
  i: byte;
  screenpos: word absolute $FE = $0400;
begin 
  screenpos:=$0400;

  for i:=1 to arow do
    screenpos := screenpos + 40;
  end;
  screenpos := screenpos + col;
  
  asm
    ldy #0
loop:
    lda ($4B),Y
    cmp #0
    beq exit
    sta ($FE),Y
    iny
    cpy #40
    bne loop
exit:
  end
  
end;
```
so the for loop is clever enough to cancel itself out if the to is lower then the initial value
was going to do something stupid in the for loop like `if arow >= 1 then`
thanks for the hint!
Also i now declared screenpos as $FE, so no more lo hi step.

Can you make it work that inside the assambly part i can reference to screenpos
the compiler does not like `sta (screenpos),Y` so i do `sta ($FE),Y` same goes for `lda ($4B),Y`

**Comment by t-edson** [comment]
Implemented the use of Pascal variables in Indirect ASM instructions:

```
  asm
    ldy #0
loop:
    lda (atext),Y
    cmp #0
    beq exit
    sta (screenpos),Y
    iny
    cpy #40
    bne loop
exit:
  end
```

**Comment by mvdhoning** [comment]
works :-)

should i close this issue as it got sidetracked a lot and solved lots of other things and open a new issue for multiplication in pascal? Not sure now what i would need it for now though.

**Comment by t-edson** [comment]
Please close the issue and open other for Multiplication.
